### PR TITLE
Duplicate Slide

### PR DESCRIPTION
**Pull request by davidheyman**
API route and front-end to duplicate slides

—

Created via [Raycast](https://www.raycast.com?ref=signatureGithub)

### CODE REVIEW

**Comment by buccalon** [comment]
image

@davidheyman I suggest changing the plus icon for `...` and duplicate in a [dropdown](https://react.semantic-ui.com/collections/menu/#content-dropdown-item), or just `duplicate`

**Comment by davidheyman** [comment]
What about removing the add card button above, and turning it into a drop down with options for add and duplicate?

**Comment by davidheyman** [comment]
Move delete slide button to dropdown

**Comment by davidheyman** [comment]
@buccalon This is ready for a final look

**Review by buccalon — APPROVED** [review]
Perfect!

**Pull request merged**
