### PR TITLE
Signup

### PR DESCRIPTION
**Pull request by davidheyman**
User signup form for #64 and all sub-features

### CODE REVIEW

**Comment by buccalon** [comment]
1. Between signup and email confirmation, I got the profile menu without being logged in:
image

2. After confirming my email, I still cannot log in:
image

**Comment by davidheyman** [comment]
@buccalon Those issues are resolved. I also blocked admin access to all non-admins which I think is the right call.

**Comment by davidheyman** [comment]
Reminder to myself to set all users `{ verified: true }` on the live database before this is merged in.

**Comment by buccalon** [comment]
Now I don't see the signup button:
image

My admin account gets the same verification issue (another email should be sent here?):
image

After setting verify:true in the panel (with my admin account) I was able to log in with a normal account.

**Comment by davidheyman** [comment]
This is expected behavior on both. Your account needed to have the verified manually applied. I'll do those to all existing accounts on the live sites.

As for the signup not appearing if you've logged in without being verified. I think that's OK. I'd rather people find the verification email instead of signing up again.

**Pull request merged**
